[DO NOT MERGE YET] Add consul-dataplane formula
hashicorp/homebrew-tap pull request #178
Opened 2022-09-15 10:48 UTC by boxofrad

Adds a formula for consul-dataplane. Should not be merged until the release artifacts are ready (note: the formula is missing checksums so will need to be regenerated).

Also adds support for "recommended" dependencies, as consul-dataplane requires Envoy but users may choose to build it themselves.

2022-09-21 19:04 UTC, mdeggies commented
Adding @alvin-huang as a reviewer, who may have more familiarity in this repo!

2022-09-22 20:49 UTC, modrake approved these changes
This looks like the only case of us using depends_on in our tap, we may want to be sure to keep a close eye on the first run of this to make sure the envoy dep resolves smoothly.

2022-09-30 19:23 UTC, pglass requested changes

2022-09-30 19:23 UTC, pglass commented on Formula/consul-dataplane.rb
> +    sha256 ""
I'll fill these in

2022-09-30 20:07 UTC, pglass approved these changes

2022-10-01 00:12 UTC, mdeggies commented
This looks good to me. I'll merge and deploy the lambda shortly

2022-10-01 00:13 UTC, merged